defaults: &defaults

development:
  database: yptkd_development
  username: postgres
  password:
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5

  # <<: *defaults
production:
# development:
#   database: dc57tjbnmppg78
#   username: hccuvwwyxrdugt
#   password: xun48thKVzS6aa3czou-x-cq95
#   host: ec2-54-83-3-38.compute-1.amazonaws.com
#   port: 5432
#   <<: *defaults

test:
  database: yptkd_test
  <<: *defaults

# production:
#   database: dc57tjbnmppg78
#   username: hccuvwwyxrdugt
#   password: xun48thKVzS6aa3czou-x-cq95
#   host: ec2-54-83-3-38.compute-1.amazonaws.com
#   port: 5432
#   <<: *defaults
